### ISSUE TITLE
getDynamicAlphaHull: object 'gshhs' not found

### ISSUE THREAD

**Issue by simonharnqvist** [ptitle/rangeBuilder#5]
Hi,

I'm getting an error when using getDynamicAlphaHull:
```
# reprex
> long <- c(1,2,3,4)
> lat <- c(4,3,2,1)
> coords <- cbind(long, lat)
> rangeBuilder::getDynamicAlphaHull(coords)

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'spTransform': object 'gshhs' not found
In addition: Warning message:
In data(gshhs, envir = environment()) : data set ‘gshhs’ not found
```

Obviously, I get the same error using my real dataset

This is using rangeBuilder 1.6, R 4.2.1 on Ubuntu 22.04, but I have managed to reproduce the problem on RStudio Cloud.

Reinstalling rangeBuilder, terra, rgdal and sp has not helped.

Any suggestions would be greatly appreciated. 

Thanks in advance
Simon

**Comment by ptitle** [comment]
Hi Simon, 

Thanks for reporting this issue. 

I think the issue might be that you have not loaded the R package, and are just calling the function with `rangeBuilder::`? Try loading the package first, and let me know if that solves the issue. I have just adjusted the code a bit so that this should now work even if the package has not first been loaded. 
Please install the package from Github, and see if that fixes the problem: `remotes::install_github('ptitle/rangeBuilder')`

That being said, even with the fix, this example results in a NULL because the default behavior is to clip the polygon according to the gshhs dataset, which is a simplified landmass dataset. But this set of dummy coordinates lands in the ocean, therefore the intersection results in an empty object. Setting clipToCoast = 'no' would be more appropriate with this set of coordinates, or choose a set of coordinates that is at least partially on land.

**Comment by simonharnqvist** [comment]
Explicitly loading the package solved the problem - that was indeed the problem. I tried with the new version and it now works with `rangeBuilder::` too. Thank you!
